### ISSUE TITLE
Created lobby not removed when Concerto crashes

### ISSUE THREAD

**Issue by abitofBaileys** [shiburizu/concerto-direct#1]
### System:
Windows 10  Pro 64bit (10.0, Build 19042)
AMD Ryzen 5 2600X (12CPUs), ~3.6GHz
NVIDIA GeForce RTX 2060
### Concerto version:
concerto6-20-2021
### Expected behavior:
When leaving a lobby the user created, the lobby gets removed
### Current behavior:
When leaving a lobby the user created, Concerto may crash and the lobby stays up (see log)
### Detailed description:
The action (leave) fails with a `Max retries exceeded` error: `ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)`
### Reproducable / steps to reproduce:
1. Create a public lobby
2. Leave the lobby
### Complete log:
https://pastebin.com/W19CCFAY

**Comment by shiburizu** [comment]
Thanks for the report. The "lobby" version of Concerto has not yet hit github and will be placed in a separate repo as the project has changed rather dramatically. I'm closing this issue for further review on my side later on as I suspect this is related to the server.
