### ISSUE TITLE
Make caster compatible with IPv6

### ISSUE THREAD

**Issue by Skavard** [shiburizu/concerto-direct#2]
There are many people with IPv6 compatible computers and they can use the ip that doesn't change often due to the IPv6 not running out unlike IPv4. It will be very helpful when hosting a game.

**Comment by shiburizu** [comment]
Concerto does not modify the source code of CCCaster which is the program that directly handles gameplay connections. Any issues related to gameplay should be filed to [Rhekar's CCCaster repository.](https://github.com/Rhekar/CCCaster)
